lesson/urls.py
from django.urls import path
from .views import view_question, quiz_completed, theory_view


app_name = 'lesson'
urlpatterns = [
    path('question/<int:question_id>/', view_question, name='view_question'),
    path('quiz_completed/', quiz_completed, name='quiz_completed'),
    path('theory/<int:theme_id>/', theory_view, name='theory_view'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    # path('', TemplateView.as_view(template_name='main_view/home.html'), name='home'),
    path('', include('user_profile.urls')),
    path('', include('main_view.urls')),
    path('', include('lesson.urls')),
]

main_view/urls.py
from django.urls import path
from .views import AboutUs, LevelList, ThemesForLevel, comments

app_name = 'main_view'

urlpatterns = [
    path('about/', AboutUs.as_view(), name='about'),
    path('levels/', LevelList.as_view(), name='levels'),
    path('level_detail/<int:level_id>/', ThemesForLevel.as_view(), name='level_detail'),
    path('', comments, name='comments'),
]

user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('signup/', views.RegisterUser.as_view(), name='signup'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

user_profile/urls.py
from django.urls import path
from .views import profile, ProfileUser

app_name = 'user_profile'
urlpatterns = [
    path('profile/', profile, name='profile'),
    path('profile_update/', ProfileUser.as_view(), name='profile_update'),

]

main_view/models.py
from django.db import models

# Create your models here.


class OurInformations(models.Model):
    name = models.CharField(max_length=20,)
    role = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=15)
    email = models.EmailField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'information'
        verbose_name_plural = 'informations'


class ListOfLevels(models.Model):
    level = models.CharField(max_length=15)
    description = models.TextField(max_length=2000)

    def __str__(self):
        return self.level

    class Meta:
        verbose_name = 'level'
        verbose_name_plural = 'levels'


class ListOfTheme(models.Model):
    choose_level = models.ForeignKey(ListOfLevels, on_delete=models.CASCADE)
    theme = models.CharField(max_length=500)
    theme_text = models.TextField(default='')

    def __str__(self):
        return self.theme

    class Meta:
        verbose_name = 'theme'
        verbose_name_plural = 'themes'


class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.created_at}"

main_view/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'text']
        labels = {
            'name': 'Username',
            'email': 'E-mail',
            'text': 'Text',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'name': forms.TextInput(attrs={'class': 'form-input'}),
            'text': forms.Textarea(attrs={'class': 'form-input'}),
        }

main_view/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from .models import OurInformations, ListOfLevels, ListOfTheme, Comment
from .forms import CommentForm
# Create your views here.


class AboutUs(generic.View):
    def get(self, request):
        creaters_list = OurInformations.objects.all()

        return render(request, 'main_view/about.html', {'creaters_list': creaters_list})


class LevelList(LoginRequiredMixin, generic.View):
    login_url = 'users:login'

    def get(self, request):
        level_list = ListOfLevels.objects.all()

        return render(request, 'main_view/levels.html', {'level_list': level_list})


class ThemesForLevel(generic.View):

    def get(self, request, level_id):
        level = get_object_or_404(ListOfLevels, pk=level_id)
        themes = ListOfTheme.objects.filter(choose_level=level)

        return render(request, 'main_view/level_detail.html', {'level': level, 'themes': themes})


def comments(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'main_view/home.html')
    else:
        form = CommentForm()
    comment = Comment.objects.all()
    return render(request, 'main_view/home.html', {'form': form, 'comment': comment})

templates/main_view/about.html
{% extends 'main_view/base.html' %}

{% block content %}
  {% for i in creaters_list %}
    <div class="card w-75">
      <div class="card-body">
        <h3 class="card-title">{{ i.name }}</h3>
        <p class="card-text">
          Роль: {{ i.role }}<br>
          Номер телефона: {{ i.phone_number }}<br>
          Электронная почта: {{ i.email }}
        </p>
      </div>
    </div>
  {% endfor %}
{% endblock %}


templates/main_view/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}GermanMastery{% endblock %}</title>
     <!-- add icon link -->
    <link rel="icon" href=
     "https://www.freepngimg.com/thumb/germany_flag/175275-waving-flag-germany-free-photo.png"
          type="image/x-icon">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
    <header>
        <a href="{% url 'main_view:comments' %}"><img src="https://www.freepngimg.com/thumb/germany_flag/175275-waving-flag-germany-free-photo.png" alt="Logo" class="logotype"></a>
        <div class="navigation">
            <a href="{% url 'main_view:about' %}"><button>About Us</button></a>
            {% if user.is_authenticated %}
            <a href="{% url 'user_profile:profile' %}"><button>{{ user.username|capfirst }}</button></a>
            <a href="{% url 'users:logout' %}"><button>Log out</button></a>
            {% else %}
            <a href="{% url 'users:signup' %}"><button>Sign Up</button></a>
            <a href="{% url 'users:login' %}"><button>Log In</button></a>
            {% endif %}
        </div>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <!-- Здесь размещается ваш footer -->
        <section class="contact">
        <h2 class="contact-title">Contact Us</h2>
        <p class="contact-info">Email: info@germanmastery.com</p>
        <p class="contact-info">Phone: +1 123-456-7890</p>
            <p>Мой подвал &copy; 2023</p>
        </section>
    </footer>
</body>
</html>

templates/main_view/home.html
{% extends 'main_view/base.html' %}

{% block content %}

<section class="introduction">
    <h1 class="introduction-title">We are German Mastery</h1>
    <a href="{% url 'main_view:levels' %}"><button class="introduction-btn">Start lessons</button></a>
</section>
<section class="advantages">
    <h2 class="advantages-title">Our Advantages</h2>
    <ul class="advantages-list">
        <li class="advantage-item">Experienced instructors</li>
        <li class="advantage-item">Interactive learning materials</li>
        <li class="advantage-item">Flexible schedule options</li>
    </ul>
</section>

<section class="card-section">
    <h1 class="card-section-title">Interesting facts</h1>
    <div class="card-block">

        <div class="card">
            <img src="https://th.bing.com/th/id/OIP.PjfeyM477x6gnRohQKPtZwHaEh?w=291&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7" alt="Course 1" class="card-image">
            <h3 class="course-text">Facts about the German language</h3>
            <p>Around 130 million people worldwide speak German as their mother tongue. German is the most widely spoken mother language and an official language in four countries in the European Union: Germany, Austria, Belgium and Luxembourg. German is also an official language in Switzerland and Liechtenstein. Moreover, around 7.5 million people in 42 countries worldwide belong to a German-speaking minority.</p>
        </div>

        <div class="card">
            <img src="https://th.bing.com/th/id/OIP.-v1z8Hj-F23Djn5g24jygwHaEK?w=327&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7" alt="Course 1" class="card-image">
            <h3 class="course-text">Facts about working in Germany</h3>
            <p>Germany has a very high level of employment - in 2016, over half of the people aged 15–64 were working (43.3m people) and unemployment was at a record low of 4.2%. Small and medium-sized enterprises (SMEs) make up around 52% of Germany’s economic output. Germany is the largest economy in the EU, with a gross domestic product (GDP) of 3.73 trillion USD - which is also the 4th highest in the world</p>
        </div>

        <div class="card">
            <img src="https://www.studying-in-germany.org/wp-content/uploads/2018/07/german-traditional-architecture.jpg" alt="Course 1" class="card-image">
            <h3 class="course-text">Culture of Germany</h3>
            <p>The people, language, and traditions are what make the German culture unique. It has had a key role in the history of Europe, and not only. English speakers call it Germany, Germans themselves call it Deutschland. Germany is known as the country of poets and thinkers. German culture has been influenced and shaped throughout Germany‘s rich history once as an important part of The Holy Roman Empire, and later on as one of the most stable economies in the world.
        </div>

    </div>
</section>
<section>
    <div class="form-comment">
        <h3>Leave a comment</h3>
        <div>
            <form method="post" action="{% url 'main_view:comments' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>

    {% for c in comment %}
            <h4>{{ c.name }}</h4>
            <p>{{ c.text }}</p>
    {% endfor %}

</section>

{% endblock %}

templates/main_view/lessons_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/main_view/level_detail.html
{% extends 'main_view/base.html' %}

{% block content %}
  <h2>Themes for Level {{ level.level }}</h2>
  <ul>
    {% for th in themes %}
      <li><a href="{% url 'lesson:theory_view' theme_id=th.id %}">{{ th.theme }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

templates/main_view/levels.html
{% extends 'main_view/base.html' %}

{% block content %}
{% for l in level_list %}
<ul>
    <li>
         <h3><a href="{% url 'main_view:level_detail' l.id %}">{{ l.level }}</a></h3>
     <p><br>{{ l.description }}<br></p>
    </li>

</ul>
{% endfor %}
{% endblock %}

