main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    # path('', TemplateView.as_view(template_name='main_view/home.html'), name='home'),
    path('', include('user_profile.urls')),
    path('', include('main_view.urls')),
    path('', include('lesson.urls')),
]

user_profile/urls.py
from django.urls import path
from .views import profile, ProfileUser

app_name = 'user_profile'
urlpatterns = [
    path('profile/', profile, name='profile'),
    path('profile_update/', ProfileUser.as_view(), name='profile_update'),

]

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from main_view.models import ListOfTheme


class ThemeProgress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    theme = models.ForeignKey(ListOfTheme, on_delete=models.CASCADE)
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} - {self.theme.theme} - Completed: {self.is_completed}"


@receiver(post_save, sender=User)
def create_user_theme_progress(sender, instance, created, **kwargs):
    if created:
        create_theme_progress_for_user(instance)


def create_theme_progress_for_user(user):
    themes = ListOfTheme.objects.all()


    for theme in themes:
        ThemeProgress.objects.create(user=user, theme=theme)

user_profile/forms.py
from django import forms
from django.contrib.auth import get_user_model


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Username', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'First name',
            'last_name': 'Last name',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

user_profile/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from lesson.utils import get_level_progress
from user_profile.forms import ProfileUserForm
from user_profile.models import ThemeProgress
from main_view.models import  ListOfLevels


class ProfileUser(UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'user_profile/profile_update.html'

    def get_success_url(self):
        return reverse_lazy('user_profile:profile')

    def get_object(self, queryset=None):
        return self.request.user


def profile(request):
    levels = ListOfLevels.objects.all()
    level_progress = []

    for level in levels:
        progress = get_level_progress(request.user, level)
        level_progress.append({'level': level, 'progress': progress})

    context = {
        'username': request.user.username,
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
        'email': request.user.email,
        'level_progress': level_progress,
    }
    return render(request, 'user_profile/profile.html', context)

templates/user_profile/profile.html
{% extends 'main_view/base.html' %}

{% block content %}
<div class="container">
    <h1>User Profile</h1>
    <p>Username: {{ username }}</p>
    <p>First Name: {{ first_name }}</p>
    <p>Last Name: {{ last_name }}</p>
    <p>Email: {{ email }}</p>


    <h3>Level Progress</h3>
    {% if level_progress %}
      <ul>
        {% for progress in level_progress %}
          <li>{{ progress.level }} - {{ progress.progress }}%</li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No level progress available.</p>
    {% endif %}
</div>

<a href="{% url 'user_profile:profile_update' %}"><button>Update</button></a>
{% endblock %}




templates/user_profile/profile_update.html
{% extends 'main_view/base.html' %}

{% block content %}
<form method="post">
     {% csrf_token %}
     {{ form.as_p }}
     <button type="submit">Update</button>
</form>
{% endblock %}